NAME_PROJECT: MASKPOSENET

LOGS_NAME: 20241205_Test_PoseTrain

SOLVERS:
  DEVICE: 'cuda:0'
  GPU_IDS: [0]
  USE_DDP: False
  SEED: 42
  OUTPUT_DIR: './middle_log'
  LOGS_NAME: '1126_train'
  TENSORBOARD_LOGS_DIR: 'logs'
  CHECKPOINTS_DIR: 'checkpoints'
  SAVE_EPOCH_FREQ: 10
  PRINT_FREQ: 10
  EPOCHS: 100
  START_EPOCH: 1
  WARMUP_EPOCHS: 0

OPTIMIZER:
  TYPE: ADAM
  LR: 0.0001
  BETAS: [ 0.5, 0.999 ]
  EPS: 0.000001
  WEIGHT_DECAY: 0.0

LR_SCHEDULER:
  TYPE: WARMUPCOSINELR
  MAX_ITERS: 600000
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000

POSE_MODEL:
  COARSE_NPOINT: 196
  FINE_NPOINT: 2048
  FEATURE_EXTRACTION:
    VIT_TYPE: VIT_BASE
    UP_TYPE: LINEAR
    EMBED_DIM: 768
    OUT_DIM: 256
    USE_PYRAMID_FEAT: TRUE
    PRETRAINED: TRUE
  GEO_EMBEDDING:
    SIGMA_D: 0.2
    SIGMA_A: 15
    ANGLE_K: 3
    REDUCTION_A: MAX
    HIDDEN_DIM: 256
  COARSE_POINT_MATCHING:
    NBLOCK: 3
    INPUT_DIM: 256
    HIDDEN_DIM: 256
    OUT_DIM: 256
    TEMP: 0.1
    SIM_TYPE: COSINE
    NORMALIZE_FEAT: TRUE
    LOSS_DIS_THRES: 0.15
    NPROPOSAL1: 6000
    NPROPOSAL2: 300
  FINE_POINT_MATCHING:
    NBLOCK: 3
    INPUT_DIM: 256
    HIDDEN_DIM: 256
    OUT_DIM: 256
    PE_RADIUS1: 0.1
    PE_RADIUS2: 0.2
    FOCUSING_FACTOR: 3
    TEMP: 0.1
    SIM_TYPE: COSINE
    NORMALIZE_FEAT: TRUE
    LOSS_DIS_THRES: 0.15

TRAIN_DATASET:
  DATA_DIR: "/home/lhy/datasets"
  DATASET_DIR: "datasets_handle_4000t_800v"
  MODEL_DIR: "models"
  TEMPLATE_DIR: "templates"
  NUM_IMG_PER_EPOCH: -1
  DEPTH_SCALE: 5.0
  IMG_SIZE: 224
  N_SAMPLE_OBSERVED_POINT: 2048
  N_SAMPLE_MODEL_POINT: 2048
  N_SAMPLE_TEMPLATE_POINT: 5000
  MIN_VISIB_FRACT: 0.1
  MIN_PX_COUNT_VISIB: 512
  SHIFT_RANGE: 0.01
  RGB_MASK_FLAG: TRUE
  DILATE_MASK: TRUE

TRAIN_DATALOADER:
  BATCH_SIZE: 4
  NUM_WORKERS: 8
  SHUFFLE: TRUE
  DROP_LAST: TRUE
  PIN_MEMORY: FALSE

TEST_DATASET:
  NAME: BOP_TEST_DATASET
  DATA_DIR: ../DATA/BOP
  DATASET_DIR: datasets
  MODEL_DIR: models
  TEMPLATE_DIR: templates
  IMG_SIZE: 224
  N_SAMPLE_OBSERVED_POINT: 2048
  N_SAMPLE_MODEL_POINT: 1024
  N_SAMPLE_TEMPLATE_POINT: 5000
  MINIMUM_N_POINT: 8
  RGB_MASK_FLAG: TRUE
  SEG_FILTER_SCORE: 0.25
  N_TEMPLATE_VIEW: 42

TEST_DATALOADER:
  BATCH_SIZE: 1
  NUM_WORKERS: 1
  SHUFFLE: FALSE
  DROP_LAST: FALSE
  PIN_MEMORY: FALSE

RD_SEED: 1
TRAINING_EPOCH: 15
ITERS_TO_PRINT: 50
